services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=redis

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order
    ports:
      - "5002:5002"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
